<?xml version="1.0"?>
<recipe>
	<dependency mavenUrl="io.reactivex.rxjava2:rxjava:2.1.0"/>
	<dependency mavenUrl="io.reactivex.rxjava2:rxandroid:2.0.1"/>
	<dependency mavenUrl="com.squareup.retrofit2:retrofit:2.2.0"/>
	<dependency mavenUrl="com.squareup.retrofit2:converter-gson:2.2.0"/>
	<dependency mavenUrl="com.squareup.retrofit2:converter-scalars:2.2.0"/>
	<dependency mavenUrl="com.squareup.retrofit2:adapter-rxjava2:2.2.0"/>
	<dependency mavenUrl="com.squareup.okhttp3:logging-interceptor:3.5.0"/>

	
    <instantiate from="root/src/app_package/httputils/config/SPConfig.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/config/SPConfig.java" />
	<instantiate from="root/src/app_package/httputils/exception/ApiException.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/exception/ApiException.java" />
	<instantiate from="root/src/app_package/httputils/fileload/download/BaseDownloadObserver.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/fileload/download/BaseDownloadObserver.java" />
	<instantiate from="root/src/app_package/httputils/fileload/download/DownloadApi.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/fileload/download/DownloadApi.java" />
	<instantiate from="root/src/app_package/httputils/fileload/download/DownloadManager.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/fileload/download/DownloadManager.java" />
	<instantiate from="root/src/app_package/httputils/fileload/download/DownloadObserver.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/fileload/download/DownloadObserver.java" />
	<instantiate from="root/src/app_package/httputils/fileload/download/DownloadRetrofit.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/fileload/download/DownloadRetrofit.java" />
    <instantiate from="root/src/app_package/httputils/fileload/download/ProgressListener.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/fileload/download/ProgressListener.java" />
	<instantiate from="root/src/app_package/httputils/fileload/upload/UploadFileApi.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/fileload/upload/UploadFileApi.java" />
	<instantiate from="root/src/app_package/httputils/fileload/upload/UploadRetrofit.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/fileload/upload/UploadRetrofit.java" />
	<instantiate from="root/src/app_package/httputils/http/GlobalHttpUtils.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/http/GlobalHttpUtils.java" />
	<instantiate from="root/src/app_package/httputils/http/HttpUtils.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/http/HttpUtils.java" />
	<instantiate from="root/src/app_package/httputils/http/OkHttpClient.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/http/OkHttpClient.java" />
	<instantiate from="root/src/app_package/httputils/http/RetrofitClient.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/http/RetrofitClient.java" />
	<instantiate from="root/src/app_package/httputils/http/SingleHttpUtils.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/http/SingleHttpUtils.java" />
	<instantiate from="root/src/app_package/httputils/interceptor/AddCookieInterceptor.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/interceptor/AddCookieInterceptor.java" />
	<instantiate from="root/src/app_package/httputils/interceptor/CacheInterceptor.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/interceptor/CacheInterceptor.java" />
	<instantiate from="root/src/app_package/httputils/interceptor/HeaderInterceptor.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/interceptor/HeaderInterceptor.java" />
	<instantiate from="root/src/app_package/httputils/interceptor/ObservableTransformer.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/interceptor/ObservableTransformer.java" />
	<instantiate from="root/src/app_package/httputils/interceptor/SaveCookieInterceptor.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/interceptor/SaveCookieInterceptor.java" />
	<instantiate from="root/src/app_package/httputils/observer/base/BaseObserver.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/observer/base/BaseObserver.java" />
	<instantiate from="root/src/app_package/httputils/observer/interfaces/ISubscriber.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/observer/interfaces/ISubscriber.java" />
	<instantiate from="root/src/app_package/httputils/observer/CommonObserver.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/observer/CommonObserver.java" />
	<instantiate from="root/src/app_package/httputils/utils/SPUtils.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/utils/SPUtils.java" />
	<instantiate from="root/src/app_package/httputils/utils/SSLUtils.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/utils/SSLUtils.java" />
	<instantiate from="root/src/app_package/httputils/utils/ToastUtils.java.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/utils/ToastUtils.java" />
	<instantiate from="root/src/app_package/httputils/readme.txt.ftl"
                   to="${escapeXmlAttribute(srcOut)}/httputils/readme.txt" />
	
	
	<open file="${escapeXmlAttribute(srcOut)}/httputils/readme.txt" />
</recipe>
